### ISSUE TITLE
Can i use IBM JsonStore in my android application without Server?

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [MobileFirst-Platform-Developer-Center/JSONStoreAndroid#1]
Can i use IBM JsonStore in my android application without Server ?? In the sample project->assets folder, there is a file called "mfpclient.properties". This file has the following config
wlServerHost=9.109.245.27
wlServerPort=9080
wlServerContext=/mfp/
languagePreferences=en

Can i use IBM JsonStore in my android application, without providing this config file. Is it mandatory to have a server to use this JsonStore ??

**Comment by vivinkrishnan** [comment]
JSONStore can be used in limited capability mode without MFP server. However, you will need the mfpclient.properties file to be present ( even if it doesn't connect to the server). This is because MFP JSONStore SDK needs MFP core SDK as a dependency.
You cannot perform syncing of the JSONStore data , without connecting to MFP server.

**Comment by kpradeepkumarreddy** [comment]
What are the default values that i can use in mfpclient.properties file, if i don't want to connect to MFP server ??
"JSONStore can be used in limited capability mode without MFP server."
What does limited capacity mean in the above line ??
We maintain our own server for syncing data. So i don't need to connect to MFP server. 
Can somebody help me with the steps to follow when not  connected to MFP server and for using our own server for data syncing ??

**Comment by kpradeepkumarreddy** [comment]
> JSONStore can be used in limited capability mode without MFP server. However, you will need the mfpclient.properties file to be present ( even if it doesn't connect to the server). This is because MFP JSONStore SDK needs MFP core SDK as a dependency.
> You cannot perform syncing of the JSONStore data , without connecting to MFP server.

What are the default values that i can use in mfpclient.properties file, if i don't want to connect to MFP server ??
"JSONStore can be used in limited capability mode without MFP server."
What does limited capacity mean in the above line ??
We maintain our own server for syncing data. So i don't need to connect to MFP server.
Can you help me with the steps to follow when not connected to MFP server and steps to follow for using our own server for data syncing ??

**Comment by vivinkrishnan** [comment]
You can keep the default values or dummy values in mfpclient.properties file.
How will you connect to your "own server" for syncing data?

**Comment by kpradeepkumarreddy** [comment]
> You can keep the default values or dummy values in mfpclient.properties file.
Dummy values means, can i use the following values:-
wlServerHost=0.0.0.0
wlServerPort=0
wlServerContext=null
languagePreferences=null

> How will you connect to your "own server" for syncing data?
Periodically in my mobile app, i get the data from server using restful api calls and write the server response data to local db json store.
