### ISSUE TITLE
Android App size increased by 20 MB

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [MobileFirst-Platform-Developer-Center/JSONStoreAndroid#2]
After adding IBM JSONStore in my android app, size increased by 20 MB.  Before adding JsonStore, app size was 18 MB and after adding JsonStore, app size is 38 MB.

How to reduce the size of this android archive file ??
ibmmobilefirstplatformfoundationjsonstore-8.0.2019082807.aar

Why JsonStore android archive file size is so big ??

**Comment by kpradeepkumarreddy** [comment]
Is there any way to reduce the size of this .aar file in android ??
Is there any alternative for IBM JSONStore ??

**Comment by vivinkrishnan** [comment]
1) You can try abi filters to remove emulator architectures.
Eg:
  Add the following to the "DefaultConfig" section of your build.gradle file.
   ndk {
      abiFilters "armeabi", "armeabi-v7a", "arm64-v8a" //use only devices supported architectures
  }
Also , refer:
https://developer.android.com/topic/performance/reduce-apk-size
https://developer.android.com/studio/build/configure-apk-splits

2) You could try custom solutions.
