### ISSUE TITLE
 IBM JSONStore  .aar file size is too big(20 MB) to be used in an android app 

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [MobileFirst-Platform-Developer-Center/JSONStoreAndroid#3]
To reduce my android app size,  i'm already using app bundles format to publish my app to play store. I want to reduce the size further. What else can i do ??

What are the custom solutions that i can try to replace IBM JSONStore ?? Can somebody give some ideas ??

**Comment by vivinkrishnan** [comment]
Use abiFilters to keep only device types. Avoid simulator types ( x86, x86_64).

For custom you will have to use your own mobile DBs and store data in it.
