### ISSUE TITLE
Dummy values in mfpclient.properties file.

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [MobileFirst-Platform-Developer-Center/JSONStoreAndroid#4]
If i don't want to connect to MFP server, can i use the following dummy values in mfpclient.properties file :-

wlServerHost=0.0.0.0
wlServerPort=0
wlServerContext=null
languagePreferences=null

**Comment by vivinkrishnan** [comment]
wlServerHost=1.2.3.4
wlServerPort=80
wlServerContext=mfp
languagePreferences=en
